### ISSUE TITLE
Externals optimization.

### ISSUE THREAD

**Issue by DylanPiercey** [rlindskog/solit#1]
Just noticed you were using [node-externals](https://github.com/rlindskog/solit/blob/master/config/server-config.js#L26) which IMO is overkill.

Thought I'd share a regex that would achieve the same thing without accessing the disk.
```js
  externals: [/^[^./!].*(?!webpack\/hot\/poll\?300|solit|\.(eot|woff|woff2|ttf|otf|svg|png|jpg|jpeg|gif|ico|mp4|mp3|ogg|swf|webp|css|scss|sass|sss|less))$/],
```

I typically just use:

```js
externals: [/^[^./!]/]
```

But the above should account for everything you were doing.

FTR I'm not saying you have to use this, feel free to close :).

**Comment by DylanPiercey** [comment]
Actually I just realized this won't work with the whitelisted modules.

Ignore me :).

**Comment by rlindskog** [comment]
@DylanPiercey That's pretty cool!
